<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <LangVersion>10.0</LangVersion>
    <WarningLevel>4</WarningLevel>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WFTools3D\WFTools3D.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Facade.jpg" />
    <Resource Include="Images\Ground.jpg" />
    <Resource Include="Images\Poster.jpg" />
    <Resource Include="Images\Sky.jpg" />
  </ItemGroup>
</Project>
